#! /usr/bin/env python

"""
runs the manual tests without the need to build and install
"""

import os
import sys
import shutil

sys.path.insert(0, "..")

import chemfigit

if __name__ == "__main__":

  if os.path.exists('output'):
    shutil.rmtree('output')

  chemfigit._chemfigit._chemfigit()

