#! /usr/bin/env python

"""
runs the manual tests without the need to build and install
"""

import os
import sys
import shutil
import logging

sys.path.insert(0, "..")

import chemfigit

if __name__ == "__main__":

  logging.basicConfig(level=logging.INFO)

  logging.info("%%%%%%%%%%%%%%%%%%%% testing %%%%%%%%%%%%%%%%%%%%")

  if os.path.exists('output'):
    logging.info("Removing 'output' directory.")
    shutil.rmtree('output')

  logging.info("Running _chemfigit()")
  chemfigit._chemfigit._chemfigit()

